server:
  port: 8081
spring:
  activemq:
    packages:
      trust-all: true
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    non-blocking-redelivery: true
activemq:
  topic: VirtualTopic.TOPIC1
logging:
  level:
    ROOT: INFO