spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
activemq:
#  topic: VirtualTopic.TOPIC

  queues:
    usual: Consumer.usualQueue.VirtualTopic.TOPIC1
    durable: Consumer.durable.VirtualTopic.TOPIC1
logging:
  level:
    ROOT: INFO